INSERT INTO quizzes (title, description, is_public, creator_id, category, quiz_url) VALUES
('Science Trivia', 'Test your knowledge of general science facts.', true, 1, 'Science', 'HZ2Yon22'),
('History Buffs', 'A quiz for history enthusiasts.', true, 2, 'History', 'gpX6w9cg'),
('Movie Mania', 'How well do you know blockbuster movies?', true, 3, 'Movies', 'khssoKAV'),
('World Capitals', 'Identify the capitals of various countries.', true, 4, 'Geography', '3w8AhdiM'),
('Famous Books', 'Match the famous book with its author.', true, 5, 'Art', '5ME7ylhj'),
('Pop Culture Quiz', 'Test your knowledge of recent trends and icons.', true, 6, 'Pop Culture', 'ZtHU6Ijc'),
('Math Puzzles', 'Solve challenging math problems.', false, 7, 'Science', '7YQDnnFG'),
('Space Exploration', 'A quiz about the history of space exploration.', true, 8, 'Space', 'mXxeOkkt'),
('Music Legends', 'Identify the artist from their popular hits.', true, 9, 'Art', 'uabJKFEC'),
('Sports Quiz', 'Trivia for sports fans across the globe.', true, 10, 'Sports', 'IZ9QEnCD'),
('Geography Genius', 'Explore the physical and political geography of the world.', false, 11, 'Geography', 'yyDSJ5nt'),
('Tech Titans', 'Know your tech giants and innovations.', true, 12, 'Technology', 'bApxcBIK'),
('Art History', 'Match famous artworks with their creators.', false, 13, 'Art', 'L5Hko7Ai'),
('Superhero Showdown', 'Trivia about popular superheroes and their stories.', true, 14, 'Superheroes', '1Zpps2Jb'),
('Programming Basics', 'Test your knowledge of basic programming concepts.', true, 15, 'Programming', 'IY8bsD3r'),
('Classic Movies', 'Guess the movie from its famous scene or dialogue.', true, 16, 'Movies', '2n2OkTgA'),
('Gaming Gurus', 'A quiz for video game enthusiasts.', true, 17, 'Pop Culture', 'N5UIdsEe'),
('Animal Kingdom', 'Learn fun facts about the animal world.', true, 18, 'Animals', 'gERCeFqS'),
('Cryptic Riddles', 'Solve tricky riddles and puzzles.', false, 19, 'Riddles', 'NagiCBBJ'),
('Space Trivia', 'Questions about planets, stars, and galaxies.', true, 20, 'Space', 's8YGJZTo');
